### PR TITLE
Fixed horrible if else fixes #106

### LINKED ISSUE #106: Change the if else statements in drop randomizer

### PR DESCRIPTION
**Pull request by Wolgo**
Jurriaan accidentally forgot to use feature/, but it's too late to change that now.

This uses an arraylist and private int's instead.

### CODE REVIEW

File: src/main/java/net/liquidpineapple/pang/objects/DropRandomizer.java [hunk 1]
```diff
@@ -11,14 +14,46 @@
...
+            randomList.add(new Drop("/sprites/drops/gemBlue.png", 0, 0, 0, 1, 1500));
+            randomList.add(new Drop("/sprites/drops/gemRed.png", 0, 0, 0, 1, 1500));
+            randomList.add(new Drop("/sprites/drops/gemYellow.png", 0, 0, 0, 1, 1500));
+            randomList.add(new Drop("/sprites/drops/gemGreen.png", 0, 0, 0, 1, 1500));
+        }
+        for (int i = 0; i < heartNum; i++) {
+            randomList.add(new Drop("/sprites/drops/heart.png", 0, 0, 0, 1, 1, 1));
+        }
+        for (int i = 0; i < nullNum; i++) {
+            randomList.add(null);
```
Comment (TMRert) [inline src/main/java/net/liquidpineapple/pang/objects/DropRandomizer.java]: It is bad practice to add a null value to an array, it would be better to insert a specific value for which you can check.

File: src/main/java/net/liquidpineapple/pang/objects/DropRandomizer.java [hunk 2]
```diff
@@ -27,37 +62,17 @@ public DropRandomizer(){
...
-        }
-        else if(68 <= roll && roll <70 ) {
-             randomDrop  = new Drop("/sprites/drops/heart.png", startX, startY, 0, 1, 1, 1);
-        }
+
+        int length = randomList.size();
+        int roll = randomizer.nextInt(length);
+        Drop randomDrop = randomList.get(roll);
+
         if( randomDrop  != null){
```
Comment (TMRert) [inline src/main/java/net/liquidpineapple/pang/objects/DropRandomizer.java]: As said above, you'd want to check for a specific value. Another implementation could be done by doing something like this:
```java
private static final int AMOUNT_OF_DROPS = 0; //specify the desired amount of drops here
...
...
int roll = randomizer.nextInt(AMOUNT_OF_DROPS);

if(roll <randomList.size()) {
Drop randomDrop = randomList.get(roll);
...
}

**Comment by Fastjur** [comment]
@TMRert Could you please accept the changes and merge so we can start refactoring?

**Comment by Wolgo** [comment]
No clue at all why it had to merge the Branch again, somehow it decided the origin branch was ahead of my local branch 😦

**Comment by Fastjur** [comment]
image
Because there weren't any...
